export const shoesList = [
    {
        id:"1",
        title: 'GRAFFITI SLIDES',
        name: 'SOLETHREADS',
        price: '30',
        images: ['Images/flip-flop1-1.jpg', 'Images/flip-flop1-2.jpg'],
        category: 'flipFlops',
        avalSize: [35, 36, 37],
        showImage : 0,
    },
    {
        id:"2",
        title: "Boy's Slipper Flip Flop",
        name: 'Shoe Mate',
        price: '80',
        images: ['Images/flip-flop2-1.jpg', 'Images/flip-flop2-2.jpg'],
        category: 'flipFlops',
        avalSize: [38, 39, 40, 47],
        showImage : 0,
    },
    {
        id:"3",
        title: 'Men Flip Flop',
        name: 'DES TONGS',
        price: '100',
        images: ['Images/flip-flop3-1.jpg', 'Images/flip-flop3-2.jpg'],
        category: 'flipFlops',
        avalSize: [41, 42, 43, 48],
        showImage : 0,
    },
    {
        id:"4",
        title: 'Mens Sliders Comfort Flip Flops',
        name: 'PERY-PAO',
        price: '120',
        images: ['Images/flip-flop4-1.jpg', 'Images/flip-flop4-2.jpg'],
        category: 'flipFlops',
        avalSize: [44, 45, 46, 49],
        showImage : 0,
    },



    {
        id:"5",
        title: "Men's Sneakers",
        name: 'Centrino',
        price: '90',
        images: ['Images/sneakers1-1.jpg', 'Images/sneakers1-2.jpg'],
        category: 'sneakers',
        avalSize: [35, 36, 37,47],
        showImage : 0,
    },
    {
        id:"6",
        title: 'ReLive Knit Casual Sneakers',
        name: "Neeman's",
        price: '60',
        images: ['Images/sneakers2-1.jpg', 'Images/sneakers2-2.jpg'],
        category: 'sneakers',
        avalSize: [38, 39, 40,48],
        showImage : 0,
    },
    {
        id:"7",
        title: "Men's Canvas Sneakers",
        name: 'Sparx',
        price: '200',
        images: ['Images/sneakers3-1.jpg', 'Images/sneakers3-2.jpg'],
        category: 'sneakers',
        avalSize: [41, 42, 43,49],
        showImage : 0,
    },
    {
        id:"8",
        title: 'Men Clarkin Sneaker',
        name: 'US Polo Association',
        price: '180',
        images: ['Images/sneakers4-1.jpg', 'Images/sneakers4-2.jpg'],
        category: 'sneakers',
        avalSize: [44, 45, 46],
        showImage : 0,
    },



    {
        id:"9",
        title: 'Oxford Class Designer Patent',
        name: 'SIR CORBETT',
        price: '300',
        images: ['Images/lace-up1-1.jpg', 'Images/lace-up1-2.jpg'],
        category: 'laceUpShoes',
        avalSize: [35, 36, 37,47],
        showImage : 0,
    },
    {
        id:"10",
        title: "Men's Synthetic Formal Lace Up",
        name: 'Allexandro',
        price: '120',
        images: ['Images/lace-up2-1.jpg', 'Images/lace-up2-2.jpg'],
        category: 'laceUpShoes',
        avalSize: [38, 39, 40, 48],
        showImage : 0,
    },
    {
        id:"11",
        title: "Men's Modern Shoes",
        name: 'Aadi',
        price: '250',
        images: ['Images/lace-up3-1.jpg', 'Images/lace-up3-2.jpg'],
        category: 'laceUpShoes',
        avalSize: [41, 42, 43, 49],
        showImage : 0,
    },
    {
        id:"12",
        title: 'Lace Up Formals for Men',
        name: 'Kraasa',
        price: '150',
        images: ['Images/lace-up4-1.jpg', 'Images/lace-up4-2.jpg'],
        category: 'laceUpShoes',
        avalSize: [44, 45, 46],
        showImage : 0,
    },



    {
        id:"13",
        title: 'Stylish Plastic Shoe Horns',
        name: 'Skudgear',
        price: '120',
        images: ['Images/accessories1-1.jpg', 'Images/accessories1-2.jpg'],
        category: 'shoeAccessories',
        avalSize: [35, 36, 37, 47],
        showImage : 0,
    },
    {
        id:"14",
        title: 'NILKANTH - Extendable Shoe',
        name: 'NIL KANTH',
        price: '220',
        images: ['Images/accessories2-1.jpg', 'Images/accessories2-2.jpg'],
        category: 'shoeAccessories',
        avalSize: [38, 39, 40, 48],
        showImage : 0,
    },
    {
        id:"15",
        title: 'Unisex Self-Adhesive Heel Cushion',
        name: 'Ewinever',
        price: '450',
        images: ['Images/accessories3-1.jpg', 'Images/accessories3-2.jpg'],
        category: 'shoeAccessories',
        avalSize: [41, 42, 43, 49],
        showImage : 0,
    },
    {
        id:"16",
        title: 'Shoe Trees for Men Adjustable',
        name: 'Lify',
        price: '50',
        images: ['Images/accessories4-1.jpg', 'Images/accessories4-2.jpg'],
        category: 'shoeAccessories',
        avalSize: [44, 45, 46],
        showImage : 0,
    },
]