export const shoesList = [
    {
        title: 'DEF',
        name: 'DEF',
        price: '30',
        images: ['Images/flip-flop1-1.jpg', 'Images/flip-flop1-2.jpg'],
        category: 'flipFlops',
        avalSize: [35, 36, 37],
        showImage : 0,
    },
    {
        title: '456',
        name: 'ABC',
        price: '80',
        images: ['Images/flip-flop2-1.jpg', 'Images/flip-flop2-2.jpg'],
        category: 'flipFlops',
        avalSize: [38, 39, 40],
        showImage : 0,
    },
    {
        title: '789',
        name: 'GHI',
        price: '100',
        images: ['Images/flip-flop3-1.jpg', 'Images/flip-flop3-2.jpg'],
        category: 'flipFlops',
        avalSize: [41, 42, 43],
        showImage : 0,
    },
    {
        title: '1011112',
        name: 'JKL',
        price: '120',
        images: ['Images/flip-flop4-1.jpg', 'Images/flip-flop4-2.jpg'],
        category: 'flipFlops',
        avalSize: [35, 36, 37],
        showImage : 0,
    },



    {
        title: '131415',
        name: 'MNO',
        price: '90',
        images: ['Images/sneakers1-1.jpg', 'Images/sneakers1-2.jpg'],
        category: 'sneakers',
        avalSize: [35, 36, 37],
        showImage : 0,
    },
    {
        title: '161718',
        name: 'PQR',
        price: '60',
        images: ['Images/sneakers2-1.jpg', 'Images/sneakers2-2.jpg'],
        category: 'sneakers',
        avalSize: [35, 36, 37],
        showImage : 0,
    },
    {
        title: '192021',
        name: 'STU',
        price: '200',
        images: ['Images/sneakers3-1.jpg', 'Images/sneakers3-2.jpg'],
        category: 'sneakers',
        avalSize: [35, 36, 37],
        showImage : 0,
    },
    {
        title: '222324',
        name: 'VWX',
        price: '180',
        images: ['Images/sneakers4-1.jpg', 'Images/sneakers4-2.jpg'],
        category: 'sneakers',
        avalSize: [35, 36, 37],
        showImage : 0,
    },



    {
        title: '252627',
        name: 'YZA',
        price: '300',
        images: ['Images/lace-up1-1.jpg', 'Images/lace-up1-2.jpg'],
        category: 'laceUpShoes',
        avalSize: [35, 36, 37],
        showImage : 0,
    },
    {
        title: '282930',
        name: 'BCD',
        price: '120',
        images: ['Images/lace-up2-1.jpg', 'Images/lace-up2-2.jpg'],
        category: 'laceUpShoes',
        avalSize: [35, 36, 37],
        showImage : 0,
    },
    {
        title: '313233',
        name: 'EFG',
        price: '250',
        images: ['Images/lace-up3-1.jpg', 'Images/lace-up3-2.jpg'],
        category: 'laceUpShoes',
        avalSize: [35, 36, 37],
        showImage : 0,
    },
    {
        title: '343536',
        name: 'HIJ',
        price: '150',
        images: ['Images/lace-up4-1.jpg', 'Images/lace-up4-2.jpg'],
        category: 'laceUpShoes',
        avalSize: [35, 36, 37],
        showImage : 0,
    },



    {
        title: '373839',
        name: 'KLM',
        price: '120',
        images: ['Images/accessories1-1.jpg', 'Images/accessories1-2.jpg'],
        category: 'shoeAccessories',
        avalSize: [35, 36, 37],
        showImage : 0,
    },
    {
        title: '404142',
        name: 'MNO',
        price: '220',
        images: ['Images/accessories2-1.jpg', 'Images/accessories2-2.jpg'],
        category: 'shoeAccessories',
        avalSize: [35, 36, 37],
        showImage : 0,
    },
    {
        title: '434445',
        name: 'PQR',
        price: '450',
        images: ['Images/accessories3-1.jpg', 'Images/accessories3-2.jpg'],
        category: 'shoeAccessories',
        avalSize: [35, 36, 37],
        showImage : 0,
    },
    {
        title: '464748',
        name: 'STU',
        price: '50',
        images: ['Images/accessories4-1.jpg', 'Images/accessories4-2.jpg'],
        category: 'shoeAccessories',
        avalSize: [35, 36, 37],
        showImage : 0,
    },
]